CREATE TABLE Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL
);

CREATE TABLE Employees (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FECHA_INGRES DATE NOT NULL,
  NOMBRE VARCHAR(255) NOT NULL,
  SALARIO INT NOT NULL
);

CREATE TABLE Requests (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CODIGO VARCHAR(255) NOT NULL,
  Descripcion VARCHAR(255) NOT NULL,
  Resumen VARCHAR(50) NOT NULL,
  ID_EMPLEADO INT,
  FOREIGN KEY (ID_EMPLEADO) REFERENCES Employees(ID)
);
